"""
Weekly AI Review Agent — VYRN

Generates a full weekly coach review every Sunday (or on demand).
The review includes:
  - Workout consistency (sessions completed / planned)
  - Strength gains (per exercise)
  - Nutrition adherence (avg protein / calories vs target)
  - Recovery score average
  - Best lift of the week (biggest weight logged)
  - Areas that need attention
  - AI-generated narrative recommendation for next week
  - Month-level body composition estimate (if weight data available)

The narrative is generated by the LLM with full context, not a template.
"""
from __future__ import annotations
import json
import logging
from datetime import date, timedelta
from dataclasses import dataclass, field

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage

from db.supabase_client import get_supabase, get_full_user_context
from db.memory_client import recall
from services.nutrition import calculate_macros
from schemas.models import Goal
from core.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


@dataclass
class WeeklyReview:
    week_label: str
    consistency_pct: int            # 0-100
    sessions_completed: int
    sessions_planned: int
    avg_recovery_score: int         # 0-10
    avg_protein_g: float
    protein_target_g: float
    protein_adherence_pct: int
    avg_calories: int
    calories_target: int
    calories_adherence_pct: int
    best_lift: dict                 # {exercise, weight_kg, reps}
    strength_gains: list[dict]      # [{exercise, prev_kg, curr_kg, delta_kg}]
    needs_attention: list[str]      # max 3 items
    highlights: list[str]           # max 3 positive highlights
    next_week_strategy: str         # LLM-generated narrative
    confidence: str                 # "Low" | "Medium" | "High"
    generated_at: str


def _week_range(weeks_ago: int = 0) -> tuple[date, date]:
    today = date.today()
    start = today - timedelta(days=today.weekday() + 7 * weeks_ago)  # Monday
    end = start + timedelta(days=6)  # Sunday
    return start, end


def _get_week_sessions(user_id: str, start: date, end: date) -> list[dict]:
    sb = get_supabase()
    res = (
        sb.table("workout_sessions")
        .select("*")
        .eq("user_id", user_id)
        .gte("session_date", str(start))
        .lte("session_date", str(end))
        .execute()
    )
    return res.data or []


def _get_week_nutrition(user_id: str, start: date, end: date) -> list[dict]:
    sb = get_supabase()
    res = (
        sb.table("nutrition_logs")
        .select("log_date, calories, protein_g")
        .eq("user_id", user_id)
        .gte("log_date", str(start))
        .lte("log_date", str(end))
        .execute()
    )
    return res.data or []


def _get_week_exercise_logs(user_id: str, start: date, end: date) -> list[dict]:
    sb = get_supabase()
    res = (
        sb.table("exercise_logs")
        .select("exercise_name, weight_kg, reps, logged_at")
        .eq("user_id", user_id)
        .gte("logged_at", str(start))
        .lte("logged_at", str(end) + "T23:59:59")
        .order("weight_kg", desc=True)
        .execute()
    )
    return res.data or []


def _get_prev_week_bests(user_id: str, prev_start: date, prev_end: date) -> dict[str, float]:
    """Returns {exercise_name: max_weight_kg} for the previous week."""
    sb = get_supabase()
    res = (
        sb.table("exercise_logs")
        .select("exercise_name, weight_kg")
        .eq("user_id", user_id)
        .gte("logged_at", str(prev_start))
        .lte("logged_at", str(prev_end) + "T23:59:59")
        .execute()
    )
    bests: dict[str, float] = {}
    for l in (res.data or []):
        ex = l.get("exercise_name", "")
        w = l.get("weight_kg") or 0
        if ex and w > bests.get(ex, 0):
            bests[ex] = w
    return bests


def _get_planned_sessions_count(user_id: str, start: date, end: date) -> int:
    """Estimate planned sessions from the active workout plan schedule."""
    sb = get_supabase()
    res = (
        sb.table("workout_plans")
        .select("schedule")
        .eq("user_id", user_id)
        .eq("is_active", True)
        .limit(1)
        .execute()
    )
    if not res.data:
        return 5  # default assumption
    schedule = res.data[0].get("schedule") or {}
    day_keys = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
    return sum(1 for k in day_keys if schedule.get(k) and schedule[k].lower() != "rest")


def _generate_narrative(
    profile: dict,
    review_data: dict,
    memories: list[str],
    llm: ChatGroq,
) -> str:
    """Use the LLM to generate a personalized next-week strategy narrative."""
    name = (profile.get("full_name") or "Athlete").split()[0]
    memories_text = "\n".join(f"- {m}" for m in memories) if memories else "No specific preferences on file."

    prompt = f"""You are VYRN — a highly personalized fitness coach.

Generate a concise, personalized NEXT WEEK strategy for {name} based on this weekly review data.

WEEKLY DATA:
{json.dumps(review_data, indent=2)}

ATHLETE PROFILE:
- Goal: {profile.get('goal', 'maintain')}
- Experience: {profile.get('experience_level', 'intermediate')}
- Phase: {profile.get('current_phase', 'general')}

COACH MEMORY (personal facts):
{memories_text}

Write a 3-4 sentence strategy in first-person coach voice. Be specific — mention actual numbers, 
specific exercises, actual adjustments. Do NOT use bullet points. 
Reference their actual data (e.g. "Your bench is up 2.5kg — add one more top set next week").
End with one clear priority action for Monday.
Maximum 80 words."""

    try:
        response = llm.invoke([
            SystemMessage(content="You are VYRN coach. Be specific, warm, data-driven. Max 80 words."),
            HumanMessage(content=prompt),
        ])
        return response.content.strip()
    except Exception as e:
        logger.warning(f"Weekly narrative generation failed: {e}")
        return "Keep the momentum going next week. Focus on progressive overload and hitting your protein target daily."


def generate_weekly_review(user_id: str, weeks_ago: int = 0) -> WeeklyReview:
    """
    Generate a full weekly review.
    weeks_ago=0 → current/most recent week
    weeks_ago=1 → last week
    """
    this_start, this_end = _week_range(weeks_ago)
    prev_start, prev_end = _week_range(weeks_ago + 1)

    profile, agent_state = get_full_user_context(user_id)

    # ── Macro targets ──────────────────────────────────────────────────────
    goal_str = profile.get("goal") or "maintain"
    goal = Goal(goal_str) if goal_str in Goal._value2member_map_ else Goal.maintain
    weight_kg = profile.get("weight_kg") or 75
    height_cm = profile.get("height_cm") or 175
    age = profile.get("age") or 28
    gender = profile.get("gender") or "male"
    targets = calculate_macros(weight_kg, height_cm, age, gender, goal, is_training_day=True)

    # ── Sessions ───────────────────────────────────────────────────────────
    sessions = _get_week_sessions(user_id, this_start, this_end)
    completed = [s for s in sessions if s.get("completed")]
    planned_count = _get_planned_sessions_count(user_id, this_start, this_end)
    consistency_pct = round(len(completed) / max(1, planned_count) * 100)

    # ── Nutrition ──────────────────────────────────────────────────────────
    nutrition_logs = _get_week_nutrition(user_id, this_start, this_end)
    by_date: dict[str, dict] = {}
    for l in nutrition_logs:
        d = l.get("log_date", "")
        if d not in by_date:
            by_date[d] = {"protein_g": 0.0, "calories": 0}
        by_date[d]["protein_g"] += l.get("protein_g") or 0
        by_date[d]["calories"] += l.get("calories") or 0

    if by_date:
        avg_protein = sum(d["protein_g"] for d in by_date.values()) / len(by_date)
        avg_calories = int(sum(d["calories"] for d in by_date.values()) / len(by_date))
    else:
        avg_protein = 0.0
        avg_calories = 0

    protein_adherence = round(avg_protein / max(1, targets["protein_g"]) * 100)
    calorie_adherence = round(avg_calories / max(1, targets["calories"]) * 100)

    # ── Exercise logs + strength gains ────────────────────────────────────
    exercise_logs = _get_week_exercise_logs(user_id, this_start, this_end)
    prev_bests = _get_prev_week_bests(user_id, prev_start, prev_end)

    # Best lift this week
    best_lift: dict = {}
    if exercise_logs:
        top = exercise_logs[0]  # already sorted by weight_kg desc
        best_lift = {
            "exercise": top.get("exercise_name", ""),
            "weight_kg": top.get("weight_kg", 0),
            "reps": top.get("reps", 0),
        }

    # Strength gains per exercise
    curr_bests: dict[str, float] = {}
    for l in exercise_logs:
        ex = l.get("exercise_name", "")
        w = l.get("weight_kg") or 0
        if ex and w > curr_bests.get(ex, 0):
            curr_bests[ex] = w

    strength_gains = []
    for ex, curr_w in curr_bests.items():
        prev_w = prev_bests.get(ex, 0)
        if prev_w > 0 and (curr_w - prev_w) >= 1.25:
            strength_gains.append({
                "exercise": ex,
                "prev_kg": prev_w,
                "curr_kg": curr_w,
                "delta_kg": round(curr_w - prev_w, 2),
            })
    strength_gains.sort(key=lambda x: x["delta_kg"], reverse=True)

    # ── Recovery ───────────────────────────────────────────────────────────
    cns = agent_state.get("cns_fatigue_score", 0)
    avg_recovery = max(0, min(10, 10 - cns))

    # ── Highlights and needs attention ────────────────────────────────────
    highlights = []
    needs_attention = []

    if consistency_pct >= 80:
        highlights.append(f"Workout consistency: {consistency_pct}% — excellent discipline this week.")
    elif consistency_pct < 60:
        needs_attention.append(f"Only {len(completed)}/{planned_count} sessions completed — consistency is slipping.")

    if strength_gains:
        top_gain = strength_gains[0]
        highlights.append(f"{top_gain['exercise']}: +{top_gain['delta_kg']}kg vs last week.")

    if protein_adherence >= 90:
        highlights.append(f"Protein averaging {avg_protein:.0f}g/day — great nutrition discipline.")
    elif protein_adherence < 70:
        needs_attention.append(f"Protein averaged only {avg_protein:.0f}g ({protein_adherence}% of target) — this is limiting recovery.")

    if avg_recovery >= 7:
        highlights.append(f"Recovery score averaging {avg_recovery}/10 — body is responding well.")
    elif avg_recovery <= 4:
        needs_attention.append(f"Recovery averaging {avg_recovery}/10 — consider more sleep and a deload.")

    if calorie_adherence < 75:
        needs_attention.append(f"Calories averaged {avg_calories} kcal ({calorie_adherence}% of target) — may be under-fueling.")

    # ── Confidence level ──────────────────────────────────────────────────
    data_richness = sum([
        len(sessions) >= 2,
        len(by_date) >= 3,
        len(exercise_logs) >= 5,
    ])
    confidence = "High" if data_richness == 3 else "Medium" if data_richness >= 1 else "Low"

    # ── LLM narrative ─────────────────────────────────────────────────────
    memories = []
    try:
        memories = recall(user_id, "weekly review training nutrition recovery", n_results=5)
    except Exception:
        pass

    review_data_for_llm = {
        "week": f"{this_start} to {this_end}",
        "sessions_completed": len(completed),
        "sessions_planned": planned_count,
        "consistency_pct": consistency_pct,
        "avg_protein_g": round(avg_protein, 1),
        "protein_target_g": targets["protein_g"],
        "avg_calories": avg_calories,
        "calories_target": targets["calories"],
        "avg_recovery": avg_recovery,
        "strength_gains": strength_gains[:3],
        "best_lift": best_lift,
        "highlights": highlights,
        "needs_attention": needs_attention,
    }

    try:
        llm = ChatGroq(
            model=settings.groq_model,
            api_key=settings.groq_api_key,
            temperature=0.4,
        )
        narrative = _generate_narrative(profile, review_data_for_llm, memories, llm)
    except Exception as e:
        logger.warning(f"LLM unavailable for weekly review: {e}")
        narrative = "Keep building on this week's work. Focus on consistency and hitting your daily protein target."

    week_label = f"{this_start.strftime('%b %d')} – {this_end.strftime('%b %d, %Y')}"

    return WeeklyReview(
        week_label=week_label,
        consistency_pct=min(100, consistency_pct),
        sessions_completed=len(completed),
        sessions_planned=planned_count,
        avg_recovery_score=avg_recovery,
        avg_protein_g=round(avg_protein, 1),
        protein_target_g=targets["protein_g"],
        protein_adherence_pct=min(100, protein_adherence),
        avg_calories=avg_calories,
        calories_target=targets["calories"],
        calories_adherence_pct=min(100, calorie_adherence),
        best_lift=best_lift,
        strength_gains=strength_gains[:5],
        needs_attention=needs_attention[:3],
        highlights=highlights[:3],
        next_week_strategy=narrative,
        confidence=confidence,
        generated_at=date.today().isoformat(),
    )
